
- name: Update ubuntu servers
  hosts: all
  become: yes
 
  tasks:
  - name: update apt
    apt:
      update_cache: yes

  - name: install apache
    package:
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started

  - name: start apache2
    service:
      name: apache2
      enabled: yes
